floral: Fix DM_SMLINKS missing
This was causing the Carrier Provision Service
app to crash with the following:
UnsatisfiedLinkError: dlopen failed: library "libdmengine.so" not found

Change-Id: I31e9d2631339ceaa6f63d69b4a342b5a30312a0c